--Crear Usuario, Correr Primera Linea
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--Correr las 2 lineas
CREATE USER PET_HEAVEN IDENTIFIED BY PET_HEAVEN ACCOUNT UNLOCK;
GRANT ALL PRIVILEGES TO PET_HEAVEN;

--Base De Datos

-- Crear la tabla Usuarios
CREATE TABLE Usuarios (
    Usuario_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Usuario VARCHAR2(100) NOT NULL,
    Correo VARCHAR2(100) NOT NULL UNIQUE,
    Contrase�a VARCHAR2(100) NOT NULL,
    Rol VARCHAR2(50) NOT NULL,
    Telefono VARCHAR2(15),
    Fecha_Creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Crear la tabla Mascotas
CREATE TABLE Mascotas (
    Mascota_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Propietario_ID NUMBER NOT NULL,
    Nombre_Mascota VARCHAR2(100) NOT NULL,
    Tipo VARCHAR2(50) NOT NULL, -- Dom�stica, Ex�tica, etc.
    Raza VARCHAR2(100),
    Peso NUMBER(5,2),
    Fecha_Registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Edad NUMBER,
    Sexo VARCHAR2(10),
    CONSTRAINT FK_Mascotas_Propietario FOREIGN KEY (Propietario_ID) REFERENCES Usuarios(Usuario_ID)
);

-- Crear la tabla Habitaciones
CREATE TABLE Habitaciones (
    Habitacion_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Habitacion VARCHAR2(100) NOT NULL,
    Estado VARCHAR2(50) NOT NULL, -- Disponible, Ocupada, En mantenimiento
    Capacidad_Maxima NUMBER NOT NULL,
    Tipo_Habitacion VARCHAR2(50) NOT NULL, -- Estandar, Premium, etc.
    Ubicacion VARCHAR2(100),
    Descripcion VARCHAR2(4000),
    Precio_Base NUMBER(10,2)
);

-- Crear la tabla Servicios
CREATE TABLE Servicios (
    Servicio_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Servicio VARCHAR2(100) NOT NULL,
    Descripcion VARCHAR2(4000),
    Precio NUMBER(10,2) NOT NULL,
    Duracion NUMBER -- Duraci�n en minutos
);

-- Crear la tabla Precios
CREATE TABLE Precios (
    Precio_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Tipo_Mascota VARCHAR2(50) NOT NULL, -- Dom�stica o Ex�tica
    Tipo_Habitacion VARCHAR2(50) NOT NULL, -- Estandar, Premium, etc.
    Precio_Diario NUMBER(10,2) NOT NULL
);

-- Crear la tabla Reservaciones
CREATE TABLE Reservaciones (
    Reservacion_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Mascota_ID NUMBER NOT NULL,
    Habitacion_ID NUMBER NOT NULL,
    Fecha_Entrada TIMESTAMP NOT NULL,
    Fecha_Salida TIMESTAMP NOT NULL,
    Estado_Reservacion VARCHAR2(50) NOT NULL, -- Pendiente, Confirmada, Cancelada
    Total NUMBER(10,2) NOT NULL,
    Notas VARCHAR2(4000),
    CONSTRAINT FK_Reservacion_Mascota FOREIGN KEY (Mascota_ID) REFERENCES Mascotas(Mascota_ID),
    CONSTRAINT FK_Reservacion_Habitacion FOREIGN KEY (Habitacion_ID) REFERENCES Habitaciones(Habitacion_ID)
);

-- Crear la tabla Servicios_Reservacion
CREATE TABLE Servicios_Reservacion (
    Servicio_Reservacion_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Reservacion_ID NUMBER NOT NULL,
    Servicio_ID NUMBER NOT NULL,
    Cantidad NUMBER NOT NULL,
    Precio NUMBER(10,2) NOT NULL,
    CONSTRAINT FK_ServicioReservacion_Reservacion FOREIGN KEY (Reservacion_ID) REFERENCES Reservaciones(Reservacion_ID),
    CONSTRAINT FK_ServicioReservacion_Servicio FOREIGN KEY (Servicio_ID) REFERENCES Servicios(Servicio_ID)
);

-- Crear la tabla Pagos
CREATE TABLE Pagos (
    Pago_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Reservacion_ID NUMBER NOT NULL,
    Monto_Total NUMBER(10,2) NOT NULL,
    Fecha_Pago TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Metodo_Pago VARCHAR2(50) NOT NULL,
    Estado_Pago VARCHAR2(50) NOT NULL, -- Completado, Pendiente, Fallido
    CONSTRAINT FK_Pago_Reservacion FOREIGN KEY (Reservacion_ID) REFERENCES Reservaciones(Reservacion_ID)
);

-- Crear la tabla Promociones
CREATE TABLE Promociones (
    Promocion_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Descripcion VARCHAR2(4000),
    Descuento NUMBER(5,2) NOT NULL,
    Fecha_Inicio TIMESTAMP NOT NULL,
    Fecha_Fin TIMESTAMP NOT NULL
);

-- Crear la tabla Logs_Disponibilidad
CREATE TABLE Logs_Disponibilidad (
    Log_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Habitacion_ID NUMBER NOT NULL,
    Estado VARCHAR2(50) NOT NULL, -- Estado actual de la habitaci�n
    Fecha_Cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Comentarios VARCHAR2(4000),
    CONSTRAINT FK_LogsDisponibilidad_Habitacion FOREIGN KEY (Habitacion_ID) REFERENCES Habitaciones(Habitacion_ID)
);

-- Crear la tabla Inventario
CREATE TABLE Inventario (
    Inventario_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Item VARCHAR2(100) NOT NULL,
    Cantidad NUMBER NOT NULL,
    Fecha_Ingreso TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Proveedor VARCHAR2(100)
);

-- Crear la tabla Proveedores
CREATE TABLE Proveedores (
    Proveedor_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Contacto VARCHAR2(100),
    Direccion VARCHAR2(4000)
);




SELECT * FROM Usuarios;
SELECT * FROM Mascotas;
SELECT * FROM Habitaciones;
SELECT * FROM Servicios;
SELECT * FROM Precios;
SELECT * FROM Reservaciones;
SELECT * FROM Servicios_Reservacion;
SELECT * FROM Pagos;
SELECT * FROM Promociones;
SELECT * FROM Logs_Disponibilidad;
SELECT * FROM Inventario;
SELECT * FROM Proveedores;







-- INSERT para la tabla Usuarios
INSERT INTO Usuarios (Nombre_Usuario, Correo, Contrase�a, Rol, Telefono) 
VALUES ('usuario1', 'usuario1@example.com', 'password123', 'admin', '123456789');

-- INSERT para la tabla Mascotas
INSERT INTO Mascotas (Propietario_ID, Nombre_Mascota, Tipo, Raza, Peso, Edad, Sexo) 
VALUES (1, 'Firulais', 'Dom�stica', 'Labrador', 30.5, 5, 'Macho');

-- INSERT para la tabla Habitaciones
INSERT INTO Habitaciones (Nombre_Habitacion, Estado, Capacidad_Maxima, Tipo_Habitacion, Ubicacion, Descripcion, Precio_Base) 
VALUES ('Habitaci�n 101', 'Disponible', 2, 'Estandar', 'Planta Baja', 'Habitaci�n con vista al jard�n', 50.00);

-- INSERT para la tabla Servicios
INSERT INTO Servicios (Nombre_Servicio, Descripcion, Precio, Duracion) 
VALUES ('Ba�o Completo', 'Servicio de ba�o y cepillado para mascotas', 25.00, 60);

-- INSERT para la tabla Precios
INSERT INTO Precios (Tipo_Mascota, Tipo_Habitacion, Precio_Diario) 
VALUES ('Dom�stica', 'Estandar', 30.00);

-- INSERT para la tabla Reservaciones
INSERT INTO Reservaciones (Mascota_ID, Habitacion_ID, Fecha_Entrada, Fecha_Salida, Estado_Reservacion, Total, Notas) 
VALUES (1, 1, TO_TIMESTAMP('2024-09-21 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-09-25 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pendiente', 200.00, 'Primera vez que se hospeda');

-- INSERT para la tabla Servicios_Reservacion
INSERT INTO Servicios_Reservacion (Reservacion_ID, Servicio_ID, Cantidad, Precio) 
VALUES (1, 1, 1, 25.00);

-- INSERT para la tabla Pagos
INSERT INTO Pagos (Reservacion_ID, Monto_Total, Metodo_Pago, Estado_Pago) 
VALUES (1, 200.00, 'Tarjeta de Cr�dito', 'Completado');

-- INSERT para la tabla Promociones
INSERT INTO Promociones (Nombre, Descripcion, Descuento, Fecha_Inicio, Fecha_Fin) 
VALUES ('Promoci�n de Verano', 'Descuento del 10% en habitaciones premium', 10.00, TO_TIMESTAMP('2024-06-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-09-30 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));

-- INSERT para la tabla Logs_Disponibilidad
INSERT INTO Logs_Disponibilidad (Habitacion_ID, Estado, Comentarios) 
VALUES (1, 'Disponible', 'Habitaci�n lista para nuevos hu�spedes');

-- INSERT para la tabla Inventario
INSERT INTO Inventario (Nombre_Item, Cantidad, Proveedor) 
VALUES ('Comida para perros', 100, 'Proveedor de Alimentos XYZ');

-- INSERT para la tabla Proveedores
INSERT INTO Proveedores (Nombre, Contacto, Direccion) 
VALUES ('Proveedor de Alimentos XYZ', 'contacto@proveedorxyz.com', 'Calle Falsa 123');
